---
title: "Lab 1: Algebra"
author: "Maximiliano Garnier Villarreal"
---

# Algebra lineal

Para trabajar con vectores y matrices en **Python** se pueden usar listas o arreglos de **numpy** y funciones de **scipy.linalg**.

In [3]:
import numpy as np
from scipy import linalg
import pandas as pd

## Vectores

Para sumar (`+`), restar (`-`) o multiplicar (`*`) vectores elemento por elemento o para el producto punto (`np.dot()`) recordar que se requiere que los vectores tengan la misma dimension.

In [ ]:
a = np.arange(1,21)          # numeros enteros consecutivos
b = np.arange(0,21,4)        # numeros del 0 al 20 cada 4
c = np.arange(30,51,4)
d = np.arange(50,19,-5)      # numeros del 50 al 20 cada 5 (decreciente)
e = np.repeat(12,8)          # numero 12 repetido 8 veces
f = np.array([1,3,5,7])      # numeros cualesquiera
g = np.tile(f, 3)            # vector fila repetido 3 veces

In [5]:
print(a * 5)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [3]:
print(a + 5)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [4]:
print(b * c)

[   0  136  304  504  736 1000]


In [5]:
print(np.dot(b,c))  # producto punto

2680


## Matrices

Para matrices recordar que para sumar o restar deben tener las mismas dimensiones y para multiplicar (`@` o `np.matmul()`) deben cumplir $A(m,n) \cdot B(n,p)$.

In [6]:
A = np.array([[1, 5], [3, 7]])
print(A)

[[1 5]
 [3 7]]


In [7]:
print(linalg.det(A))    # determinante de matriz

-7.999999999999999


In [ ]:
print(linalg.eig(A))    # eigen values y vectors de A

In [8]:
print(linalg.inv(A))    # inversa de A

[[-0.875  0.625]
 [ 0.375 -0.125]]


In [9]:
print(A.T)              # transpuesta de A

[[1 3]
 [5 7]]


In [10]:
print(A[0,])            # fila 1, todas las columnas (todas las columnas)

[1 5]


In [11]:
print(A[1,0])           # fila 2, columna 1 (1 elemento)

3


In [12]:
A[1,0] = 15      # reemplaza el elemento en fila 2 columna 1 por 15
print(A)

[[ 1  5]
 [15  7]]


In [13]:
B = np.array([[11, 15], [13, 17]])
  
print(A + B)   # suma de matrices

[[12 20]
 [28 24]]


In [14]:
print(A @ B) # multiplicacion de matrices

[[ 76 100]
 [256 344]]


In [15]:
print(A @ np.array([[2],[5]])) # multplicacion de matriz y vector

[[27]
 [65]]


Arreglos (vectores) se pueden convertir en matrices usando `np.reshape()`, donde se especifican las dimensiones de la nueva matriz/arreglo. Si se quiere especificar solo una dimension, se puede usar `-1` para que **Python** calcule automaticamente la otra dimension.

In [16]:
print(a.reshape(4,5))  # convierte vector a matriz de 4 filas y 5 columnas

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
print(a.reshape(-1,4))  # convierte vector a matriz con 4 columnas y filas automáticas

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


Si se tiene un dataframe de **pandas**, con solo columnas numericas, se puede convertir a matriz usando el metodo `df.to_numpy()`.

In [18]:
datos = pd.read_csv("data/ABOC.csv")
 
C = datos.to_numpy() # convierte dataframe en matriz
print(C)

[[  10   17 -665]
 [  21   89 -613]
 [  33   38 -586]
 [  35   20 -440]
 [  47   58 -544]
 [  60   18 -343]
 [  65   74 -455]
 [  82   93 -437]
 [  89   60 -354]
 [  97   15 -142]]
